##
# 
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import('env')

import os

# gather sources
l_sources = [ 'solvers/Roe.cpp',
              'solvers/f_solver.cpp',
              'patches/WavePropagation1d.cpp',
              'patches/WavePropagation2d.cpp',
              'patches/WavePropagationAdaptiveGrid2d.cpp',
              'setups/DamBreak1d.cpp',
              'setups/ShockShock1d.cpp',
              'setups/RareRare1d.cpp',
              'setups/Bathymetry1d.cpp',
              'setups/SubcriticalFlow1d.cpp',
              'setups/HydraulicJump1d.cpp',
              'setups/TsunamiEvent1d.cpp',
              'setups/CircularDamBreak2d.cpp',
              'setups/DamBreak2d.cpp',
              'setups/Checkpoint2d.cpp',
              'io/NetCdf.cpp',
              'io/NetCdfReader.cpp',
              'io/NetCdfCheckpoint.cpp',
              'setups/ArtificialTsunami2d.cpp',
              'setups/TsunamiEvent2d.cpp',
              'io/Csv.cpp', 
              'io/Station.cpp',
              'io/XmlReader.cpp',
              'config/Config.cpp',
              'factory/SetupFactory.cpp',
              'core/Initializer.cpp',
              'core/InitializerAdaptiveGrid.cpp',
              'io/OutputManager.cpp']

sources = [env.Object(s) for s in l_sources]

# gather unit tests
l_tests = [ 'tests.cpp',
            'solvers/Roe.test.cpp',
            'solvers/f_solver.test.cpp',
            'patches/WavePropagation1d.test.cpp',
            'patches/WavePropagation2d.test.cpp',
            'io/Csv.test.cpp',
            'setups/DamBreak1d.test.cpp',
            'setups/ShockShock1d.test.cpp',
            'setups/RareRare1d.test.cpp',
            'setups/Bathymetry1d.test.cpp',
            'setups/SubcriticalFlow1d.test.cpp',
            'setups/HydraulicJump1d.test.cpp',
            'setups/TsunamiEvent1d.test.cpp',]

tests = [env.Object(s) for s in l_tests]

standalone = env.Object( "main.cpp" )

Return('sources tests standalone')