##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
# @section DESCRIPTION
# Continuous integration using GitHub Actions.
##
name: Tsunami Lab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Static Code Analysis
        run:
          nix-shell --pure --run "
            cppcheck src/ --template=gcc --force --error-exitcode=1
          "

      - name: Sanitize
        run: |
          nix-shell --pure --run "
            scons mode=debug+san &&
            ./build/tests &&
            ./build/tsunami_lab 25 &&
            scons mode=release+san &&
            ./build/tests &&
            ./build/tsunami_lab 500
          "

      - name: Valgrind
        run: |
          nix-shell --pure --run "
            scons mode=debug &&
            valgrind ./build/tests &&
            valgrind ./build/tsunami_lab 25
          "
          
      - name: Release
        run: |
          nix-shell --pure --run "
            scons &&
            ./build/tests &&
            ./build/tsunami_lab 500
          "